MyTruckCo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^demo/', include('demo.urls')),
]

demo/urls.py
from django.conf.urls import url

from .import views

app_name = 'demo'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/', views.about, name='about'),
	url(r'^contact/', views.contact, name='contact'),
	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

demo/models.py
from django.db import models


class Album(models.Model):
    name = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=250)

    def __str__(self):
        return self.album_title

class Picture(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    photos = models.CharField(max_length=250)

demo/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album

def index(request):
	all_albums = Album.objects.all()
	return render(request, 'demo/index.html', {'all_albums': all_albums})

def about(request):
	return render(request, 'demo/about.html')

def contact(request):
	return render(request, 'demo/contact.html')

def detail(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'demo/detail.html', {'album': album})

demo/templates/demo/about.html
{% extends 'demo/base.html' %}
{% block body %}

<h1>This is our About us page</h1>

{% endblock %}

demo/templates/demo/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>	
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'demo/style.css' %}">

</head>
<body>

	<div>
		<div class="navbar-base">
			<a href="{% url 'demo:index' %}">Home</a>
			<a href="{% url 'demo:about' %}">About Us</a>
			<a href="{% url 'demo:contact' %}">Contact Us</a>
		</div>
	</div>
	{% block body %}
	{% endblock %}

</body>
</html>

demo/templates/demo/contact.html
{% extends 'demo/base.html' %}
{% block body %}

<h1>This is our contact page</h1>

{% endblock %}

demo/templates/demo/detail.html
{% extends 'demo/base.html' %}
{% block body %}


<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.name }}</h3>

<ul>
	{% for photo in album.picture_set.all %}
	<li>{{ photos.photos }}</li>
	{% endfor %}
</ul>

{% endblock %}

demo/templates/demo/index.html
{% extends 'demo/base.html' %}
{% block body %}

{% if all_albums %}
	<h4>My Photos</h4>
	<ul>
		{% for album in all_albums %}
			<li><a href="{% url 'demo:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
		</ul>
{% else %}
	<h3>You don't have any photos yet</h3>
{% endif %}

{% endblock %}